Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Alias:
  Enabled: false

Documentation:
  Enabled: false

UselessAssignment:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

StructInheritance:
  Exclude:
    - 'app/policies/**/*'

OutputSafety:
  Exclude:
    - 'app/helpers/devise_helper.rb'

RedundantSelf:
  Exclude:
    - 'app/models/**/*'

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  TargetRubyVersion: 2.3